tags:
  minio: false

stateStore:
  minio:
    enabled: false

  oss:
    enabled: true
    region: cn-hangzhou
    bucket: risingwave
    root: risingwave
    useInternalEndpoint: false
    authentication:
      useServiceAccount: false
      accessKey: ak
      secretAccessKey: sk