tags:
  minio: false

stateStore:
  minio:
    enabled: false

  s3:
    enabled: true
    endpoint: s3-compatible-service-domain:9000
    region: us-east-1
    bucket: risingwave
    authentication:
      useServiceAccount: false
      accessKey: ak
      secretAccessKey: sk