{{/*
Copyright RisingWave Labs
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.stateStore.azblob.enabled (not .Values.stateStore.azblob.authentication.useServiceAccount) }}
{{- if empty .Values.stateStore.azblob.authentication.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "risingwave.azblobCredentialsSecretName" . }}
  labels:
    {{- include "risingwave.labels" . | nindent 4 }}
  {{- $annotations := (include "risingwave.annotations" . ) | trim }}
  {{- if $annotations }}
  annotations:
    {{ nindent 4 $annotations }}
  {{- end }}
stringData:
  AZBLOB_ACCOUNT_NAME: {{ .Values.stateStore.azblob.authentication.accountName }}
  AZBLOB_ACCOUNT_KEY: {{ .Values.stateStore.azblob.authentication.accountKey }}
{{- end }}
{{- end }}