{{/*
Copyright RisingWave Labs
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and (not .Values.tags.etcd) .Values.metaStore.etcd.authentication.enabled }}
{{- if not .Values.metaStore.etcd.authentication.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "risingwave.etcdCredentialsSecretName" . }}
  labels:
    {{- include "risingwave.labels" . | nindent 4 }}
  {{- $annotations := (include "risingwave.annotations" . ) | trim }}
  {{- if $annotations }}
  annotations:
    {{ nindent 4 $annotations }}
  {{- end }}
stringData:
  RW_ETCD_USERNAME: {{ .Values.metaStore.etcd.authentication.username | quote }}
  RW_ETCD_PASSWORD: {{ .Values.metaStore.etcd.authentication.password | quote }}
{{- end }}
{{- end }}