{{/*
Copyright RisingWave Labs
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.stateStore.gcs.enabled (not .Values.stateStore.gcs.authentication.useServiceAccount) }}
{{- if empty .Values.stateStore.gcs.authentication.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "risingwave.gcsCredentialsSecretName" . }}
  labels:
    {{- include "risingwave.labels" . | nindent 4 }}
  {{- $annotations := (include "risingwave.annotations" . ) | trim }}
  {{- if $annotations }}
  annotations:
    {{ nindent 4 $annotations }}
  {{- end }}
stringData:
  GOOGLE_APPLICATION_CREDENTIALS: {{ .Values.stateStore.gcs.authentication.credentials }}
{{- end }}
{{- end }}