{{/*
Copyright RisingWave Labs
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.stateStore.oss.enabled (not .Values.stateStore.oss.authentication.useServiceAccount) }}
{{- if empty .Values.stateStore.oss.authentication.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "risingwave.ossCredentialsSecretName" . }}
  labels:
    {{- include "risingwave.labels" . | nindent 4 }}
  {{- $annotations := (include "risingwave.annotations" . ) | trim }}
  {{- if $annotations }}
  annotations:
    {{ nindent 4 $annotations }}
  {{- end }}
stringData:
  OSS_ACCESS_KEY_ID: {{ .Values.stateStore.oss.authentication.accessKey }}
  OSS_ACCESS_KEY_SECRET: {{ .Values.stateStore.oss.authentication.secretAccessKey }}
{{- end }}
{{- end }}