{{/*
Copyright RisingWave Labs
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.stateStore.s3.enabled (not .Values.stateStore.s3.authentication.useServiceAccount) }}
{{- if empty .Values.stateStore.s3.authentication.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "risingwave.s3CredentialsSecretName" . }}
  labels:
    {{- include "risingwave.labels" . | nindent 4 }}
  {{- $annotations := (include "risingwave.annotations" . ) | trim }}
  {{- if $annotations }}
  annotations:
    {{ nindent 4 $annotations }}
  {{- end }}
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.stateStore.s3.authentication.accessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.stateStore.s3.authentication.secretAccessKey }}
{{- end }}
{{- end }}